### ISSUE TITLE
关于训练集与验证集的问题

### ISSUE THREAD

**Issue by mikurules** [LinHong-HIT/USOD10K#4]
您好，请问您论文中的结果是否是将训练集和验证集最后融合到一起作为训练集进行训练得出的网络评分？包括您的方法与所有其他对比方法？
感谢

**Comment by LinHong-HIT** [comment]
Hi，在训练TC-USOD和SOTA方法时，训练集和验证集是合并了的，测试集用于测试

**Comment by mikurules** [comment]
好的，感谢
